[package]
name = "iprev"
version = "0.1.0"
authors = ["Wes Roberts <g0r6p@a.zinc.email>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
